version: '3'
services:
  jenkins:
    build: . # Certifique-se de que o Dockerfile está no mesmo diretório
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Monta o socket do Docker
    privileged: true # Necessário para Docker-in-Docker
    environment:
      - DOCKER_DRIVER=overlay2
volumes:
  jenkins_home:
