- hosts: all
  tasks:
    - name: Remover imagem para nova contrução
      docker_image:
        force_absent: yes
        state: absent
        name: leandroSalesCotrim/docker-dotnet-core
        tag: latest

    - name: Copiar arquivos da aplicação para o host destino
      copy:
        src: /var/jenkins_home/workspace/build-donet-image/
        dest: /home/ansible/

    - name: Construir a imagem Docker
      docker_image:
        name: leandroSalesCotrim/docker-dotnet-core
        tag: latest
        source: build
        build:
          path: /home/ansible/docker-dotnet-core
      register: build_output
      ignore_errors: yes

    - name: Verificar se a imagem Docker foi criada
      shell: docker images -q leandroSalesCotrim/docker-dotnet-core
      register: image_id

    - name: Falhar se a imagem não foi encontrada
      fail:
        msg: "A imagem Docker não foi encontrada após a construção."
      when: image_id.stdout == "" 
      
    - name: Imagem Docker criada com sucesso
      debug:
        msg: "A imagem Docker foi construída e verificada com sucesso. ID da imagem: {{ image_id.stdout }}"